link to pd/n agnostic -lcurses
Somehow linking to pdcurses on linux will cause a bunch of linker errors (undefined reference to SDL stuff).  But simply linking to -lcurses works ok.  Don't know if need to specify that windows should specifically use pdcurses or if simply -lcurses suffices.